### ISSUE TITLE
Examples show localhost instead of domain

### ISSUE THREAD

**Issue by luksireiku** [timothycrosley/hug#527]
![image](https://user-images.githubusercontent.com/11174915/27724664-31054336-5d73-11e7-8fc6-f6268f37dda9.png)
Read title

**Comment by IanJSeattle** [comment]
This problem appears to have been resolved between being reported and now.

**Comment by timothycrosley** [comment]
@IanJSeattle thanks for looking into this!

**Comment by luksireiku** [comment]
It's still happening to me, it may be something related with gunicorn or nginx?

**Comment by luksireiku** [comment]
Just checked it, I forgot something in my nginx config, works right now.
